### ISSUE TITLE
The website of the repo description is still the original material theme

### ISSUE THREAD

**Issue by kleo-dev** [t3dotgg/vsc-material-but-i-wont-sue-you#7]

**Comment by yphastos** [comment]
Second this. Due to the recent drama of the original extension being banned/removed, and the dev going rogue, you should remove the link to the previous site, e.g. here:

![Image](https://github.com/user-attachments/assets/8f923742-e317-4d04-94f3-12a9914e45f2)

**Comment by cdbattags** [comment]
~This was fixed by Theo's commits this week~ ahhh the repo link

**Comment by yphastos** [comment]
@kleo-dev why did you closed the issue as completed? the link is still there, and would potentially lead users to a site that can then redirect them to anything, specially due to the attitude the original dev has had towards all this... it is kinda dangerous to keep that link.

please add more details of why you closed it if possible, I'm voting to reopen it, because it is NOT fixed yet.

**Comment by selimaj-dev** [comment]
I thought it was solved at first, but i posted this issue and it's @t3dotgg 's responsibility to change it, not mine

**Comment by yphastos** [comment]
@kleo-dev sorry, you are right, you can't reopen it yourself. I thought creators of issues could reopen their own, but I see only the repo owners can.
Anyway, I hope @t3dotgg can look into this!

**Comment by selimaj-dev** [comment]
I can reopen it now
